### ISSUE TITLE
New Logo Design Contribution

### ISSUE THREAD

**Issue by ihtiht** [tomastrajan/medium-enhanced-stats#1]
Hey @tomastrajan  I am a graphic designer. I support them by making design contributions to open source projects. You can see my works from my profile. I liked the Medium Enhanced Stats chrome  extension.  And I designed a logo. I hope you need a logo. You can see my designs below. 

![design_result](https://user-images.githubusercontent.com/36369736/42339350-6934865e-8095-11e8-80d8-87abd3b57c5c.jpg)

![views](https://user-images.githubusercontent.com/36369736/42339355-6e621ff6-8095-11e8-81d0-297f207c9fdc.jpg)

Do you like it? Which do you like if you like it? Do not hesitate to tell if there is something you want to change or add. 

I will be waiting for your feedback ..

**Comment by tomastrajan** [comment]
Hi @ihtiht !

Thank you very much for your effort. I am very happy that you like the extension. Can I ask you for the feedback about the original logo? What was your idea when you saw it and what motivated you to propose new logo?

Cheers!

**Comment by ihtiht** [comment]
The original logo used a font and a few bars at the back. This is very complicated because the size of the chrome extension icons is small. I wanted to make a modern design that looks good in small sizes. at the same time, I designed a logo that emphasizes the function of the application.

**Comment by tomastrajan** [comment]
@ihtiht thank you for your explanation. I still prefer and will keep original logo. Wish you all the best and who knows, maybe we can collaborate in the future on some other open source project!

Cheers!
